pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
				dir("SoftwareIntegration")
				{
					bat 'mvn -B -DskipTests clean package'
				}
            }
        }
        stage('Deliver') { 
            steps {
				dir("SoftwareIntegration")
				{
					bat './jenkins/scripts/deliver.sh'
				}
            }
        }
    }
}