pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
				dir("SoftwareIntegration")
				{
					bat 'mvn -B -DskipTests clean package'
				}
            }
        }
        stage('Test') {
            steps {
				dir("SoftwareIntegration")
				{
					bat 'mvn test'
				}
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
				dir("SoftwareIntegration")
				{
					bat './jenkins/scripts/deliver.sh'
				}
            }
        }
    }
}